### ISSUE TITLE
Problems with faculties.rive::

### ISSUE THREAD

**Issue by imSrbh** [krshrimali/ChatBot-IIITNR#1]
Tested On https://play.rivescript.com/

Query Example::

+ [who is] training and placement faculty [at] [iiit] [nr]
- Dr. Amit Kumar Agrawal

+ [who is] registrar [at] [iiit] [nr]
- Dr B.K Panigrahy

+[who is] warden [of] [girl hostel] [bose house] [iiit] [nr]
- Sresha Yadav nee Ghosh

+ [who is] warden [of] [boy hostel] [raman house] [iiit] [nr]
- Dr. Manoj Kumar Majumder

+ [who is] warden [of] [boy hostel] [bhabha house] [iiit] [nr]
- Dr Vivek Tiwari

Output Result::
**User:**warden
**Bot:**Sresha Yadav nee Ghosh

**Comment by krutikabapat** [comment]
We will use if/ else and * function more extensively so that it becomes easier for the user.

**Comment by imSrbh** [comment]
I tried but it doesn't work..
